# Generated by Django 3.0.8 on 2020-09-24 07:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(choices=[('Notebooks', 'Notebooks'), ('Smartphones', 'Smartphones'), ('Cars', 'Cars'), ('Cameras', 'Cameras'), ('Home appliances', 'Home appliances'), ('Apartments', 'Apartments'), ('Other', 'Other')], max_length=50)),
                ('article_taken', models.URLField(blank=True, max_length=500, null=True)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='users/article/images')),
                ('video', models.FileField(blank=True, null=True, upload_to='users/article/videos')),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
